version: '3'
services:
  nginx:
    image: nginx
    ports:
    - "8080:80"
    volumes:
    - nginx_html:/usr/share/nginx/html/
    networks: 
      - appnet
  centos:
    image: centos
    entrypoint: "sleep"
    command: "36000"
    depends_on:
    - nginx
    networks: 
    - appnet
volumes:
  nginx_html: {}
networks:
  appnet: 